### ISSUE TITLE
leg_pos description not clear for combined maps (mf_prop_typo for instance)

### ISSUE THREAD

**Issue by rysebaert** [riatelab/mapsf#11]
leg_pos description should be : 	
"position of the legend, **two** of 'topleft', 'top','topright', 'right', 'bottomright', 'bottom', 'bottomleft', 'left' or a vector of two coordinates in map units (c(x, y)). If leg_pos is 'n' then the legend is not plotted".

Moreover, is it possible to set two vectors of coordinates in map units for positioning manually two legend positions with leg_pos ?

**Comment by rCarto** [comment]
Nice catch for the first remark. 

Not possible (yet?) for the second.
I'm not sure how to do it. 
`leg_pos = c(x1, y1, x2, y2)` ? 
What would you expect?

**Comment by rysebaert** [comment]
legend_pos = c(x1, y1, x2, y2) returns nothing at the moment, without error message. But instinctively I would code an document it like this ! If complicated to implement, a solution could be to suggest in the documentation to use mf_legend for that purpose.

**Comment by rCarto** [comment]
OK, I'll try leg_pos = c(x1, y1, x2, y2).

**Comment by rCarto** [comment]
but then there is also these unsettling cases:
```
leg_pos = c("topright", 1, 2)
leg_pos = c(2, 3, "topright")
```

**Comment by rysebaert** [comment]
perfect, many thanks !

**Comment by rCarto** [comment]
Err, I haven't done any change yet. I keep the issue open for now

**Comment by rysebaert** [comment]
Yes, sorry ! For your previous comment, the unsettling case could not be clarified by the following description ? 
"position of the legend, two of 'topleft', 'top','topright', 'right', 'bottomright', 'bottom', 'bottomleft', 'left' or a vector of two coordinates in map units (c(x, y)). leg_pos argument must be equals to  c("position", "position") or c("position", x2, y2) or c(x1,y1, "position") or c(x1, y1, x2, y2). If leg_pos is 'n' then the legend is not plotted".
