### ISSUE TITLE
Integration with {maptiles}

### ISSUE THREAD

**Issue by PaulC91** [riatelab/mapsf#12]
Hi there, 

Firstly thanks for this package. I really like the ease in which you can map data with appropriate legends, colours and breaks.

I'm wondering if it is possible to easily integrate the plots with a maptile from the [maptile package](https://github.com/riatelab/maptiles)? 

I'm often mapping epidemiological indicators at quite a granular admin/health boundary level so a basemap helps to give context to the surrounding area, and I feel like without one, the shapefile will always appear like an island.

Thanks,
Paul

**Comment by rCarto** [comment]
Hello, 
That's possible using development version of both packages. 

``` r
library(remotes)
install_github("riatelab/maptiles")
install_github("riatelab/mapsf")
```

`maptiles` produces `SpatRaster` objects from `terra`, you have to convert them to `RasterBrick` from `raster`. Then you can use  `mf_raster()` to plot them. 


``` r
library(mapsf)
#> Le chargement a nécessité le package : sf
#> Linking to GEOS 3.7.1, GDAL 3.1.2, PROJ 7.1.0
library(maptiles)
library(osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
library(raster)
#> Le chargement a nécessité le package : sp

# Extract Barcelona municipality from osm with osmdata
q0 <- opq(bbox = "Barcelona, Spain")
q1 <- add_osm_feature(opq = q0, key = 'name', value = "Barcelona")
res1 <- osmdata_sf(q1)
bcn <- st_geometry(res1$osm_multipolygons[1,])

# use EPSG:3857 crs
bcn <- st_transform(bcn, crs = 3857)

# get osm tiles
tiles <- get_tiles(bcn, zoom = 12)

# transform to raster
tiles <- brick(tiles)
#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj =
#> prefer_proj): Discarded ellps WGS 84 in Proj4 definition: +proj=merc +a=6378137
#> +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null
#> +wktext +no_defs +type=crs
#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj =
#> prefer_proj): Discarded datum World Geodetic System 1984 in Proj4 definition

# display tiles
mf_theme("candy")
mf_raster(tiles)
mf_map(bcn, add = T, col = NA, border = "tomato", lwd = 3)
mf_title("Barcelona")
mf_credits(txt = get_credit("OpenStreetMap"), bg = "#ffffffCC")
mf_scale(5)
```

![](https://i.imgur.com/B0Fd0kq.png)

<sup>Created on 2021-04-13 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

If you want to export the map with the tiles nicely rendered (no resampling), you have to use the tiles dimensions in `mf_init()` and `interpolate = FALSE` in `mf_raster()`

``` r
mf_init(tiles, theme = "candy", 
        export = "png", filename = "barcelona.png", 
        width = dim(tiles)[2])
mf_raster(tiles, add = TRUE, interpolate = FALSE)
mf_map(bcn, add = TRUE, col = NA, border = "tomato", lwd = 3)
mf_title("Barcelona")
mf_scale(5)
mf_credits(txt = get_credit("OpenStreetMap"), bg = "#ffffffCC")
dev.off()
```
![barcelona](https://user-images.githubusercontent.com/3041254/114551818-32549a00-9c64-11eb-8e8c-255dc5978a71.png)

**Comment by PaulC91** [comment]
Impeccable! Merci beaucoup.

**Comment by rCarto** [comment]
Mais de rien :-)
