### ISSUE TITLE
mf_map() doesn't produce "typo" map of categorical variable: no error given

### ISSUE THREAD

**Issue by francisbarton** [riatelab/mapsf#13]
I have an `sf` object that works fine when piped straight to `mf_map` - it just makes a grey default base map of the areas.
One of the variables in my `sfc` tibble is a categorical variable (factor) — each area is assigned to a decile from 1 to 10. As this is not a continuous variable, I don't want to use a choropleth approach. The deciles are strictly categorical and ordered, not continuous.

`mapsf` is not producing any output for me when I use `type = "typo"`. Nothing is plotted, no error message is provided.

here's my (pseudo) code:

```
my_sf_object %>%
  mapsf::mf_map(var = "regional_decile", type = "typo", pal = "Viridis")
```

If I use `type = "choro"` instead, I get a legend but still no map. Am I missing a step?

**Comment by rCarto** [comment]
Hello, 
Based on information you have provided (use of factor, tibble...) I can produce this working example:
``` r
library(magrittr)
mtq <- mapsf::mf_get_mtq()
mtq$STATUS <- as.factor(mtq$STATUS)
mtq <- sf::st_as_sf(tibble::as_tibble(mtq))
mtq %>% mapsf::mf_map(var = "STATUS", type = "typo", pal = "Viridis")
```

![](https://i.imgur.com/I1WnDfB.png)

<sup>Created on 2021-04-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.5 (2021-03-31)
#>  os       Debian GNU/Linux 10 (buster)
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  fr_FR.UTF-8                 
#>  ctype    fr_FR.UTF-8                 
#>  tz       Europe/Paris                
#>  date     2021-04-14                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
#>  backports     1.2.1   2020-12-09 [1] CRAN (R 4.0.3)
#>  class         7.3-18  2021-01-24 [4] CRAN (R 4.0.5)
#>  classInt      0.4-3   2020-04-07 [1] CRAN (R 4.0.0)
#>  cli           2.4.0   2021-04-05 [1] CRAN (R 4.0.5)
#>  crayon        1.4.1   2021-02-08 [1] CRAN (R 4.0.5)
#>  curl          4.3     2019-12-02 [1] CRAN (R 4.0.0)
#>  DBI           1.1.1   2021-01-15 [1] CRAN (R 4.0.3)
#>  digest        0.6.27  2020-10-24 [1] CRAN (R 4.0.3)
#>  dplyr         1.0.5   2021-03-05 [1] CRAN (R 4.0.4)
#>  e1071         1.7-6   2021-03-18 [1] CRAN (R 4.0.4)
#>  ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.0)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.0)
#>  fansi         0.4.2   2021-01-15 [1] CRAN (R 4.0.3)
#>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
#>  generics      0.1.0   2020-10-31 [1] CRAN (R 4.0.3)
#>  glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
#>  highr         0.8     2019-03-20 [1] CRAN (R 4.0.0)
#>  htmltools     0.5.1.1 2021-01-22 [1] CRAN (R 4.0.3)
#>  httr          1.4.2   2020-07-20 [1] CRAN (R 4.0.2)
#>  KernSmooth    2.23-18 2020-10-29 [4] CRAN (R 4.0.5)
#>  knitr         1.31    2021-01-27 [1] CRAN (R 4.0.3)
#>  lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.0.4)
#>  magrittr    * 2.0.1   2020-11-17 [1] CRAN (R 4.0.3)
#>  mapsf         0.1.1   2021-03-01 [1] CRAN (R 4.0.5)
#>  mime          0.10    2021-02-13 [1] CRAN (R 4.0.4)
#>  pillar        1.6.0   2021-04-13 [1] CRAN (R 4.0.5)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.0)
#>  proxy         0.4-25  2021-03-05 [1] CRAN (R 4.0.4)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.0)
#>  R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.3)
#>  Rcpp          1.0.6   2021-01-15 [1] CRAN (R 4.0.3)
#>  reprex        2.0.0   2021-04-02 [1] CRAN (R 4.0.5)
#>  rlang         0.4.10  2020-12-30 [1] CRAN (R 4.0.3)
#>  rmarkdown     2.7     2021-02-19 [1] CRAN (R 4.0.4)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
#>  sf            0.9-8   2021-03-17 [1] CRAN (R 4.0.4)
#>  stringi       1.5.3   2020-09-09 [1] CRAN (R 4.0.2)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.0)
#>  styler        1.4.1   2021-03-30 [1] CRAN (R 4.0.4)
#>  tibble        3.1.0   2021-02-25 [1] CRAN (R 4.0.4)
#>  tidyselect    1.1.0   2020-05-11 [1] CRAN (R 4.0.0)
#>  units         0.7-1   2021-03-16 [1] CRAN (R 4.0.4)
#>  utf8          1.2.1   2021-03-12 [1] CRAN (R 4.0.4)
#>  vctrs         0.3.7   2021-03-29 [1] CRAN (R 4.0.4)
#>  withr         2.4.1   2021-01-26 [1] CRAN (R 4.0.3)
#>  xfun          0.22    2021-03-11 [1] CRAN (R 4.0.4)
#>  xml2          1.3.2   2020-04-23 [1] CRAN (R 4.0.0)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.0)
#> 
#> [1] /home/tim/R/x86_64-pc-linux-gnu-library/4.0
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
```

</details>

Can you send me a reproducible example of your problem (data & code)?

**Comment by francisbarton** [comment]
Thanks for your quick response. Yes I know it's better to provide a reprex but first of all I wanted to make sure I wasn't missing something obvious, as it's the first time I've used `mapsf`. Previously I have been using `tmap`.

I have been trying for a couple of hours now to work out how to provide an sf object via `dput` or `dump` and I have not managed to succeed. The output appears OK in the console but when I try to get it onto my clipboard so I can use it in a reprex, it seems to write only an incomplete version to my clipboard. I can't find any guidance online on using dput with sf.

So, no reprex yet - I'm trying!

What I have discovered in this process is that when I filter my data to provide a small subset, some subsets work OK with the code I was using, and some do not — they produce no output. The ones that work have a geometry column that is uniform, eg all of type `POLYGON`. The subsets that do not work are mixed `MULTIPOLYGON` and `POLYGON`.

Is this an issue with my data, do you think, or with this package? I don't think I had this problem of plotting mixed geometry types with `tmap`. Thank you again for your time and attention, and any ideas.

**Comment by francisbarton** [comment]
Passing my data to `sf::st_cast()` before `mf_map` has enabled me to plot the full dataset successfully!

**Comment by rCarto** [comment]
Well, I will investigate this issue of mixed geomeyries. Thank you for this helpful feedback!

**Comment by rCarto** [comment]
6c61385   should fix the initial problem
