### ISSUE TITLE
Upcoming sf release will break mapsf (due to switching to s2)

### ISSUE THREAD

**Issue by edzer** [riatelab/mapsf#15]
Please see https://github.com/r-spatial/sf/issues/1649 for details, and consider commenting there in case you have issues. (this may be a tough one - I would start trying to use `st_make_valid()` on the failing geometry, but this may well be a deeper issue, needing a better worldmap that is valid on S2 @paleolimbot).
```
Running examples in ‘mapsf-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: mf_inset_on
> ### Title: Plot an inset
> ### Aliases: mf_inset_on mf_inset_off
>
> ### ** Examples
>
> mtq <- mf_get_mtq()
> mf_map(mtq)
> mf_inset_on(x = mtq[1, ], cex = .2)
> mf_map(mtq[1, ])
> mf_inset_off()
>
> mf_map(mtq)
> mf_inset_on(x = "worldmap", pos = "bottomleft")
> mf_worldmap(x = mtq)
Error in s2_geography_from_wkb(x, oriented = oriented, check = check) :
  Loop 7 is not valid: Edge 171 crosses edge 174
Calls: mf_worldmap -> suppressMessages -> withCallingHandlers
Execution halted
```

**Comment by rCarto** [comment]
Thanks, I'll take care of it and update the package.

**Comment by edzer** [comment]
We might be able to fix this on the sf side; see the issue there.

**Comment by rCarto** [comment]
The function is working fine with `sf::sf_use_s2(FALSE)`. 
I did not succeed in making the same transformations with s2, using different world maps. 
I'll get back to it for a next release, when the s2 usage in sf will be stabilized and my understanding better.  
In the meantime, I'm just going to bypass the use of s2 in this function.
