### ISSUE TITLE
horizontal legend

### ISSUE THREAD

**Issue by sylvaine31** [riatelab/mapsf#19]
Hi,
I enjoy mapsf, but I often miss the possibility to put an horizontal legend, especially for chloropeths.

**Comment by WarmlyWilson** [comment]
Hi,

Thanks for having such a good pkg. But I am wondering how to change the sample map and input a new map such as London or Manchester? many thanks,

**Comment by samueltriviere** [comment]
Bonjour,

merci pour votre package qui est très pratique pour créer des cartes. 
L'organisation dans laquelle je travaille dispose d'une charte graphique où pour les analyses choroplethes on doit faire une légende horizontale. Serait-ce possible que vous développiez cette option dans votre package ?

merci, 
cordialement,

samuel

**Comment by rCarto** [comment]
Bonjour, 
Cette fonctionnalité est prévue pour une prochaine version. 
T.

**Comment by rCarto** [comment]
This feature is planned for a future version of the package.

**Comment by samueltriviere** [comment]
> Bonjour, Cette fonctionnalité est prévue pour une prochaine version. T.

Bonjour,

super,

merci pour votre retour,

samuel

**Comment by samueltriviere** [comment]
Bonjour,

toujours sur la légende,
je n'arrive pas à avoir un fond blanc opaque avec bg="white" dans mf_legend alors que ça marche très bien dans mf_credits.

![image](https://user-images.githubusercontent.com/124143780/218067083-cd9ea9bf-0c93-4b07-9395-f17ea81faa20.png)


merci à vous,

samuel

**Comment by rCarto** [comment]
Bonjour, 

Il me serait plus facile de vous répondre avec un exemple reproductible (ou *reprex*, voir https://thinkr.fr/reprex-ou-comment-demander-de-laide-efficacement/). 

Pour vous répondre, le problème n’apparaît pas avec ma machine : 

``` r
library(mapsf)
m <- mf_get_mtq()
bks <- mf_get_breaks(m$MED, nbreaks = 8, breaks = "quantile")
mf_map(m, 'MED', "choro",
       breaks = bks, 
       pal = "Viridis", 
       leg_pos = NA)
mf_legend(type = "choro", 
          title = "Very very long title to make the legend overlap the map",
          pos = "topleft", 
          val = bks, 
          pal = "Viridis", 
          frame = TRUE, 
          bg = "white")
```

![](https://i.imgur.com/bEBRRNf.png)

<sup>Created on 2023-02-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


Je pense qu'il s'agit plutôt d'un problème d'ordre de superposition des couches. La légende est elle bien appelée après `mf_map(..., type = "choro", leg_pos = NA)`?

**Comment by samueltriviere** [comment]
Bonjour,

c'est bien ça, j'ai mis mf_legend à la fin, juste avant mf_credits et c'est
parfait

merci encore

[image: image.png]



Le ven. 10 févr. 2023 à 12:35, Timothée Giraud ***@***.***> a
écrit :
