### ISSUE TITLE
Overlap on published raster overlaid with polygons

### ISSUE THREAD

**Issue by Wycology** [riatelab/mapsf#24]
I have raster, polygon, and points of the same extent and projection. I managed to plot them using mapsf and they aligned perfectly well. Why was there mismatch on the published output on rpubs platform? Here is the link to my output https://rpubs.com/Wyclife/raster_vector and the code is: (selec is polygon and spg is points, clima is a raster stack)

mf_init(selec, theme = 'default')
mf_shadow(selec, col = 'blue', cex = 3, add = TRUE)
mf_raster(clima2[[3]], add = T)
mf_map(selec,
       type = 'choro',
       var = 'gdp_cap_est',
       pal = 'Mint',
       add = TRUE,
       alpha = 0,
       border = 'blue')
mf_label(selec, var = 'name', col = 'red', cex = 1)
mf_map(spg2, col = 'purple', add = T)
mf_arrow()
mf_scale()

**Comment by rCarto** [comment]
Hi, 
I see the mismatch on Rpubs. But I don't know how to reproduce your figure. 
Can you post a [reproducible example](https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-create-one/5219) of your problem, so I can test it?

**Comment by Wycology** [comment]
Thanks for the speedy response. I have developed a script for reproducible example. However, this time round, the published output has no mismatch. Still struggling to know what I did here which I did not do in the previous code.

[mismatch_reproducible.txt](https://github.com/riatelab/mapsf/files/6747530/mismatch_reproducible.txt)

**Comment by rCarto** [comment]
I'll pay attention to any issue relevant to this kind of mismatch. I thought it could have been related to CRS but...
(thanks for my first encounter with the new base pipe in real life :smile: )
