### ISSUE TITLE
Ronds proportionnels

### ISSUE THREAD

**Issue by maudrna** [riatelab/mapsf#27]
Bonjour,
Je ne sais pas comment faire pour réaliser une suite de cartes avec des ronds qui soient proportionnels entre elles. Existe-t-il une fonction pour fixer une valeur maximale commune à plusieurs cartes ?
En vous remerciant.

Hello,
I don’t know how to make a series of maps with rounds that are proportional to each other. Is there a function to set a common maximum value for multiple maps?
Thank you.

**Comment by rysebaert** [comment]
Bonjour,
Vous pouvez renseigner l'argument val_max associé à la fonction mf_prop. La taille des figurés de vos différentes cartes seront ainsi comparables. 

Hello,
You can set the val_max parameter associated to the mf_prop function. The size of the symbols displayed in your series of maps will thus be comparable.

**Comment by maudrna** [comment]
Merci !
Thank you !

**Comment by rysebaert** [comment]
:)
