### ISSUE TITLE
Custom font family

### ISSUE THREAD

**Issue by jdlom** [riatelab/mapsf#28]
Hi,
Is there an easy way (or a tricky one) to use a custom font family ?
Best regards,

**Comment by rCarto** [comment]
Yes sure, something like `par(family="name of the font")` before creating the map should work. 
You can also use `family=...` in `mf_export()`.

**Comment by jdlom** [comment]
Thanks ! The code below works like a charm.
```
windowsFonts("Marianne" = "Marianne")
par(family = "Marianne")
```
