### ISSUE TITLE
adding ... to do.call(mf_map_*()) functions 

### ISSUE THREAD

**Issue by joshualerickson** [riatelab/mapsf#3]
Love the package! Seriously making it easier to produce high quality graphs. Could you add the ... to the do.call(mf_map_*()) functions? Wanting to reverse pallete in mf_map(). Thanks!

**Comment by rCarto** [comment]
Thanks! I'm not sure I understand your request. Can you provide an example of what it would look like ? 
Adding ... is not that simple as several functions with ... args are involved.
To reverse colors I would use `hcl.colors()` (or `mf_get_pal()`) directly:
``` r
library(mapsf)
#> Le chargement a nécessité le package : sf
#> Linking to GEOS 3.7.1, GDAL 3.1.2, PROJ 7.1.0
m <- mf_get_mtq()
mf_map(x = m, var = "MED", type = "choro", 
       breaks = "quantile", nbreaks = 6, 
       pal = hcl.colors(n = 6, palette = "Viridis", rev = TRUE))
```

![](https://i.imgur.com/qIz7CZL.png)

<sup>Created on 2021-03-08 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by joshualerickson** [comment]
Ahhh, yeah that's much better. '...' like you said is not always a simple solution and just calling the function directly is a better-less confusing option. Good call. Thanks.
