### ISSUE TITLE
exporting with multiple mf_map() calls

### ISSUE THREAD

**Issue by jghen1** [riatelab/mapsf#35]
I'm having trouble exporting my map after multiple mf_map() calls to plot different layers. Sometimes it exports but the picture is cropped and when I change the width it doesn't export at all. I get this error if I try to c() the x values with mf_export()
Error in UseMethod("st_bbox") : 
  no applicable method for 'st_bbox' applied to an object of class "list"

Still new to mapping entirely in R, sorry if it's a silly question. Thanks!

**Comment by rCarto** [comment]
Hello, 
Can you provide a reproductible example please? It would be easier for me to help. 
mf_export() will output a figure that fits x ratio if only one of width or heigth is set. So increasing width is not helping here.

**Comment by rCarto** [comment]
It is actually a good idea to use a combination of spatial objects to center the map on a group of layers. Your error is related to the fact that a combination of sf objects will give a list (not a valid input for `mf_export()`). But you can combine sfc objects (sf geometries):

``` r
library(mapsf)
#> Le chargement a nécessité le package : sf
#> Linking to GEOS 3.9.0, GDAL 3.2.2, PROJ 7.1.0
mtq <- mf_get_mtq()
# 1 polygon
a <- mtq[1, ]
# 1 point
b <- st_centroid(mtq[7, ])
#> Warning in st_centroid.sf(mtq[7, ]): st_centroid assumes attributes are constant
#> over geometries of x
# use c() with geometries only
mf_export(x = c(st_geometry(a), st_geometry(b)))
mf_map(mtq, add = TRUE)
mf_map(a, add = TRUE, col = "red")
mf_map(b, add = TRUE, col = "blue", pch = 20, cex = 2)
dev.off()
#> png 
#>   2
```

![map](https://user-images.githubusercontent.com/3041254/142831710-948f05a7-7803-4bb1-be47-080940321546.png)


<sup>Created on 2021-11-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jghen1** [comment]
Sorry for the slow reply. I was trying to find a good dataset to use in a reprex. I essentially had a California county shapefile that I plotted with two separate points shapefiles overlaid on top to show powerplant locations and locations of air quality sensors. I'll try the geometries approach tonight. In the future, I'll ask questions with reprex as well. My master's program does everything in ArcGIS but I want to do be able to do it all in R. Slowly learning, thank you!

**Comment by rCarto** [comment]
No problem
