### ISSUE TITLE
Integrate data points

### ISSUE THREAD

**Issue by fredericlabouyrie** [riatelab/mapsf#37]
Hello,
I am new to the R software. I try to integrate data points from the PGM_Gard database, in order to visualize them on my map_Gard map (https://geoservices.ign.fr/ocsge). I can't do it. Can someone give me some advice?
I can visualize the map OCCUPATION_SOL, according to the advice of Timothée Giraud.

> setwd("/Users/frede/OneDrive/Documents/R/OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06/OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06/OCS_GE/1_DONNEES_LIVRAISON_2019-09-00096/OCSGE_1-1_SHP_LAMB93_D30_2015")
> library(RColorBrewer)
> library(sf)
Linking to GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1; sf_use_s2() is TRUE
> library(mapsf)
> map_Gard <- st_read("OCCUPATION_SOL.shp") # Données carto occsol 
Reading layer `OCCUPATION_SOL' from data source 
  `C:\Users\frede\OneDrive\Documents\R\OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06\OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06\OCS_GE\1_DONNEES_LIVRAISON_2019-09-00096\OCSGE_1-1_SHP_LAMB93_D30_2015\OCCUPATION_SOL.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 415420 features and 8 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 721015.4 ymin: 6263149 xmax: 848021.3 ymax: 
Projected CRS: RGF93 / Lambert-93

> PGM_Gard<- read.csv2(file = "/Users/frede/OneDrive/Documents/PGM_Gard.csv",header = TRUE) # Données présence espèce Gard
> head (PGM_Gard)
   ID      X       Y
1  1 805076 6317468
2  2 830312  #6313449
3  3 770532 6312107
4  4 827693 6316687
5  5 729433 6334594
6  6 792656 6320284

**Comment by rCarto** [comment]
Hello, 
This question is not related to `mapsf`. 

If you want to transform a `data.frame` with longitude and latitude data to an `sf POINT` object you have to use `st_as_sf()` : 

``` r
library(sf)
#> Linking to GEOS 3.9.0, GDAL 3.2.2, PROJ 7.1.0; sf_use_s2() is TRUE
mdf <- data.frame(id = c(1, 2, 3), 
                  x = c(10, 20, 30), 
                  y = c(40, 41, 42))
mypoints <- st_as_sf(mdf, coords = c("x", "y"), crs = "epsg:4326")
plot(mypoints, graticule=st_crs(4326), axes = T)
```

![](https://i.imgur.com/Q6EdfTw.png)

<sup>Created on 2022-01-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by fredericlabouyrie** [comment]
Hello and thank you very much for your answer.

I had found the solution in the last few days, making progress little by little : 

PGM_30 <- sf::st_as_sf(x = PGM_Gard, coords = c("X", "Y") , crs = 2154)

head (PGM_30)
Simple feature collection with 6 features and 1 field
Geometry type: POINT
Dimension: XY
Bounding box: xmin: 729433 ymin: 6312107 xmax: 830312 ymax: 6334594
Projected CRS: RGF93 / Lambert-93
  IND geometry
1 1 POINT (805076 6317468)
2 2 POINT (830312 6313449)
3 3 POINT (770532 6312107)
4 4 POINT (827693 6316687)
5 5 POINT (729433 6334594)
6 6 POINT (792656 6320284)

This is now what I get with your recommendations.
library(sf)
Linking to GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1; sf_use_s2() is TRUE
 PGM_30 <- sf::st_as_sf(x = PGM_Gard, coords = c("X", "Y") , crs = 2154)
 plot(PGM_30, graticule=st_crs(2154), axes = T

![Rplot](https://user-images.githubusercontent.com/97049564/149152924-e0eb1c5f-b1fb-4c0f-92cc-3f096c2db559.jpeg)

What I would like to do is to visualise this point of presence layer (with a single colour) on the shapefile map_Gard (occsol).

Best regards.

**Comment by fredericlabouyrie** [comment]
Hello, 
you understood well, despite my inconsistencies = Overlay the map of points of presence of the species (PGM_30) on the map of land use OCCUPATION_SOL (Map_Gard)
My problematics = Make a nice and readable map for everyone. 
My main preoccupation = invert the color of the palette and make the points of presence readable on the map.

I have to admit that I am still not comfortable with the reprex system :

![image](https://user-images.githubusercontent.com/97049564/149614916-d858eda6-12ca-4094-94cd-d25953c23141.png)

Here is the map I get for now : 
![map](https://user-images.githubusercontent.com/97049564/149615066-ab743712-b856-4ac4-a3a4-e608143c9ec3.png)


My script : 
> setwd("/Users/frede/OneDrive/Documents/R/OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06/OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06/OCS_GE/1_DONNEES_LIVRAISON_2019-09-00096/OCSGE_1-1_SHP_LAMB93_D30_2015")


> library(RColorBrewer)
> display.brewer.pal(11,"RdYlGn")
> library(sf)
Linking to GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1; sf_use_s2() is TRUE
> library(mapsf)


> map_Gard <- st_read("OCCUPATION_SOL.shp")
Reading layer `OCCUPATION_SOL' from data source 
  `C:\Users\frede\OneDrive\Documents\R\OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06\OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06\OCS_GE\1_DONNEES_LIVRAISON_2019-09-00096\OCSGE_1-1_SHP_LAMB93_D30_2015\OCCUPATION_SOL.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 415420 features and 8 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 721015.4 ymin: 6263149 xmax: 848021.3 ymax: 6375578
Projected CRS: RGF93 / Lambert-93


> PGM_Gard<- read.csv2(file = "/Users/frede/OneDrive/Documents/PGM_Gard.csv",header = TRUE)
> PGM_30 <- sf::st_as_sf(x = PGM_Gard, coords = c("X", "Y") , crs = 2154)
> head (PGM_30)
Simple feature collection with 6 features and 1 field
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 729433 ymin: 6312107 xmax: 830312 ymax: 6334594
Projected CRS: RGF93 / Lambert-93
  IND               geometry
1   1 POINT (805076 6317468)
2   2 POINT (830312 6313449)
3   3 POINT (770532 6312107)
4   4 POINT (827693 6316687)
5   5 POINT (729433 6334594)
6   6 POINT (792656 6320284)

> mf_export(map_Gard, width = 1500)

> mf_map(x = map_Gard, type = "typo", var = "CODE_CS", pal = "RdYlGn", border = NA, add = TRUE)
> mf_map(PGM_30, add = TRUE)

> dev.off()

**Comment by rCarto** [comment]
reverse palette & more visible points:
```r
my_pal <- hcl.colors(n = 11,  palette = "RdYlGn", rev = TRUE)
mf_map(x = map_Gard, type = "typo", var = "CODE_CS", pal = my_pal, border = NA, add = TRUE)
mf_map(PGM_30, pch = 21, col = "red", cex = 1.5, add = TRUE)
```

**Comment by fredericlabouyrie** [comment]
Hello and thank you!
By now , I can't open the file from the IGN site: [ftp://BD_ALTI_ext:docoazeecoosh1Ai@ftp3.ign.fr/BDALTIV2_2-0_25M_ASC_LAMB93-IGN69_D030_2020-07-10.7z](url).
``` r
setwd("/Users/frede/OneDrive/Documents/R/BDALTIV2_2-0_25M_ASC_LAMB93-IGN69_D030_2020-07-10/BDALTIV2/1_DONNEES_LIVRAISON_2021-10-00008/BDALTIV2_MNT_25M_ASC_LAMB93_IGN69_D030")
getwd()
#> [1] "C:/Users/frede/OneDrive/Documents/R/BDALTIV2_2-0_25M_ASC_LAMB93-IGN69_D030_2020-07-10/BDALTIV2/1_DONNEES_LIVRAISON_2021-10-00008/BDALTIV2_MNT_25M_ASC_LAMB93_IGN69_D030"

library(sf)
#> Linking to GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1; sf_use_s2() is TRUE
library(mapsf)
library(raster)
#> Le chargement a nécessité le package : sp
library(sp)
read.asciigrid("/Users/frede/OneDrive/Documents/R/BDALTIV2_2-0_25M_ASC_LAMB93-IGN69_D030_2020-07-10/BDALTIV2/1_DONNEES_LIVRAISON_2021-10-00008/BDALTIV2_MNT_25M_ASC_LAMB93_IGN69_D030")
#> Warning in file(fname, "r"): impossible d'ouvrir le fichier '/
#> Users/frede/OneDrive/Documents/R/BDALTIV2_2-0_25M_ASC_LAMB93-
#> IGN69_D030_2020-07-10/BDALTIV2/1_DONNEES_LIVRAISON_2021-10-00008/
#> BDALTIV2_MNT_25M_ASC_LAMB93_IGN69_D030' : Permission denied
#> Error in file(fname, "r"): impossible d'ouvrir la connexion
```

<sup>Created on 2022-01-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by fredericlabouyrie** [comment]
And use mapsf to visualize it.
Best regards.

**Comment by rCarto** [comment]
:+1:  for using the `reprex` package.

You need to use `rast` from `terra` package to import the raster in SpatRaster format (suitable format for display in `mapsf`)

I think you should have a look at these 2 documents that cover most of the points raised in this issue:
1. https://rcarto.github.io/geomatique_avec_r/
2. https://rcarto.github.io/cartographie_avec_r/
``` r
library(terra)
#> terra 1.5.12
library(mapsf)
#> Le chargement a nécessité le package : sf
#> Linking to GEOS 3.9.0, GDAL 3.2.2, PROJ 7.1.0; sf_use_s2() is TRUE
ras <- rast("/home/tim/BDALTIV2_2-0_25M_ASC_LAMB93-IGN69_D030_2020-07-10/BDALTIV2/1_DONNEES_LIVRAISON_2021-10-00008/BDALTIV2_MNT_25M_ASC_LAMB93_IGN69_D030/BDALTIV2_25M_FXX_0700_6350_MNT_LAMB93_IGN69.asc")
mf_raster(ras)
```

![](https://i.imgur.com/Y324WTP.png)

<sup>Created on 2022-01-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by fredericlabouyrie** [comment]
Hello,
I would like to know if it is possible to transform a shapefile into a raster format,  and then view it in mapsf with the same resolution. I would like to realise a sdm of a bird species, , after formatting all my files.

``` r
library(sf)
#> Linking to GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1; sf_use_s2() is TRUE
library(mapsf)

setwd("/Users/frede/OneDrive/Documents/R/OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06/OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06/OCS_GE/1_DONNEES_LIVRAISON_2019-09-00096/OCSGE_1-1_SHP_LAMB93_D30_2015")

map_Gard <- st_read("OCCUPATION_SOL.shp")
#> Reading layer `OCCUPATION_SOL' from data source 
#>   `C:\Users\frede\OneDrive\Documents\R\OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06\OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06\OCS_GE\1_DONNEES_LIVRAISON_2019-09-00096\OCSGE_1-1_SHP_LAMB93_D30_2015\OCCUPATION_SOL.shp' 
#>   using driver `ESRI Shapefile'
#> Simple feature collection with 415420 features and 8 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: 721015.4 ymin: 6263149 xmax: 848021.3 ymax: 6375578
#> Projected CRS: RGF93 / Lambert-93
```

<sup>Created on 2022-01-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rCarto** [comment]
https://rcarto.github.io/geomatique_avec_r/les-donn%C3%A9es-raster-le-package-terra.html#transformation-et-conversion

**Comment by fredericlabouyrie** [comment]
Hello,
I would like to change the order of the colours in my divergent palette, RdYlGn.
Example: 
Code CS 2.1.1.1 (wooded formations) to dark green colour and use a light green gradient to go to the more open environments, Code CS 2.1.3 (vineyards) in burgundy pink,
Code CS 1.2.2 (water) in light blue Do I need to create my own palette? I've tried this: it obviously doesn't work. I need your help.
Do I need to create my own palette?
I've tried this: it obviously doesn't work. I require your help!
My script : 
``` r
library(colorspace)
library(sf)
#> Linking to GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1; sf_use_s2() is TRUE
library(mapsf)
library(RColorBrewer)

# Donnees IGN OCSGE GARD
setwd("/Users/frede/OneDrive/Documents/R/OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06/OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06/OCS_GE/1_DONNEES_LIVRAISON_2019-09-00096/OCSGE_1-1_SHP_LAMB93_D30_2015")

# Carte occsol Gard
map_Gard <- st_read("OCCUPATION_SOL.shp")
#> Reading layer `OCCUPATION_SOL' from data source 
#>   `C:\Users\frede\OneDrive\Documents\R\OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06\OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06\OCS_GE\1_DONNEES_LIVRAISON_2019-09-00096\OCSGE_1-1_SHP_LAMB93_D30_2015\OCCUPATION_SOL.shp' 
#>   using driver `ESRI Shapefile'
#> Simple feature collection with 415420 features and 8 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: 721015.4 ymin: 6263149 xmax: 848021.3 ymax: 6375578
#> Projected CRS: RGF93 / Lambert-93

# Palette
my_pal <- hcl.colors(n = 11,  palette = "RdYlGn", rev = FALSE)
display.brewer.pal(n=11 , "RdYlGn" )
```

![](https://i.imgur.com/lrNKzNf.png)

``` r

# Donnees repro PGM faune LR
PGM_Gard<- read.csv2(file = "/Users/frede/OneDrive/Documents/PGM_Gard.csv",header = TRUE)
PGM_30 <- sf::st_as_sf(x = PGM_Gard, coords = c("X", "Y") , crs = 2154)

# Restitution
mf_export(map_Gard, width = 1500)
mf_map(x = map_Gard, type = "typo", var = "CODE_CS", pal =  "RdYlGn" , border = NA, add = FALSE)
mf_map(PGM_30, pch = 21, col = "red", cex = 1.5, add = TRUE)
       
mf_title("Gard")
mf_arrow("topright")
dev.off
#> function (which = dev.cur()) 
#> {
#>     if (which == 1) 
#>         stop("cannot shut down device 1 (the null device)")
#>     .External(C_devoff, as.integer(which))
#>     dev.cur()
#> }
#> <bytecode: 0x000000001d05bee0>
#> <environment: namespace:grDevices>
```

<sup>Created on 2022-08-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by fredericlabouyrie** [comment]
I try this :
``` r
# Palette_2
hcl.pals("diverging")
#>  [1] "Blue-Red"      "Blue-Red 2"    "Blue-Red 3"    "Red-Green"    
#>  [5] "Purple-Green"  "Purple-Brown"  "Green-Brown"   "Blue-Yellow 2"
#>  [9] "Blue-Yellow 3" "Green-Orange"  "Cyan-Magenta"  "Tropic"       
#> [13] "Broc"          "Cork"          "Vik"           "Berlin"       
#> [17] "Lisbon"        "Tofino"
my_pal2 <- hcl.colors(n = 11,  palette = "Red-Green", rev = TRUE)
cols <- mf_get_pal(n = c(5, 6), pal = c("Reds 2", "Greens"), rev = c(FALSE, TRUE))
#> Error in mf_get_pal(n = c(5, 6), pal = c("Reds 2", "Greens"), rev = c(FALSE, : impossible de trouver la fonction "mf_get_pal"
plot(1:11, rep(1, 11), bg = cols, pch = 22, cex = 4)
#> Error in plot.xy(xy, type, ...): objet 'cols' introuvable
```

![](https://i.imgur.com/8WIgsqr.png)

``` r
mf_map(x = map_Gard, type = "typo", var = "CODE_CS", pal =  "Red-Green" , border = NA, add = FALSE, rev = TRUE)
#> Error in mf_map(x = map_Gard, type = "typo", var = "CODE_CS", pal = "Red-Green", : impossible de trouver la fonction "mf_map"
```

<sup>Created on 2022-08-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rCarto** [comment]
> Hello, I would like to change the order of the colours in my divergent palette, RdYlGn. Example: Code CS 2.1.1.1 (wooded formations) to dark green colour and use a light green gradient to go to the more open environments, Code CS 2.1.3 (vineyards) in burgundy pink, Code CS 1.2.2 (water) in light blue Do I need to create my own palette? I've tried this: it obviously doesn't work. I need your help. Do I need to create my own palette? I've tried this: it obviously doesn't work. I require your help! My script :
> 
> ```r
> library(colorspace)
> library(sf)
> #> Linking to GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1; sf_use_s2() is TRUE
> library(mapsf)
> library(RColorBrewer)
> 
> # Donnees IGN OCSGE GARD
> setwd("/Users/frede/OneDrive/Documents/R/OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06/OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06/OCS_GE/1_DONNEES_LIVRAISON_2019-09-00096/OCSGE_1-1_SHP_LAMB93_D30_2015")
> 
> # Carte occsol Gard
> map_Gard <- st_read("OCCUPATION_SOL.shp")
> #> Reading layer `OCCUPATION_SOL' from data source 
> #>   `C:\Users\frede\OneDrive\Documents\R\OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06\OCS_GE_1-1_2015_SHP_LAMB93_D030_2019-09-06\OCS_GE\1_DONNEES_LIVRAISON_2019-09-00096\OCSGE_1-1_SHP_LAMB93_D30_2015\OCCUPATION_SOL.shp' 
> #>   using driver `ESRI Shapefile'
> #> Simple feature collection with 415420 features and 8 fields
> #> Geometry type: POLYGON
> #> Dimension:     XY
> #> Bounding box:  xmin: 721015.4 ymin: 6263149 xmax: 848021.3 ymax: 6375578
> #> Projected CRS: RGF93 / Lambert-93
> 
> # Palette
> my_pal <- hcl.colors(n = 11,  palette = "RdYlGn", rev = FALSE)
> display.brewer.pal(n=11 , "RdYlGn" )
> ```
> 
> ![](https://camo.githubusercontent.com/555a2c6366b796664c71998b85e195437ef804b11421ef57b33952ccdf38247a/68747470733a2f2f692e696d6775722e636f6d2f6c724e4b7a4e662e706e67)
> 
> ```r
> # Donnees repro PGM faune LR
> PGM_Gard<- read.csv2(file = "/Users/frede/OneDrive/Documents/PGM_Gard.csv",header = TRUE)
> PGM_30 <- sf::st_as_sf(x = PGM_Gard, coords = c("X", "Y") , crs = 2154)
> 
> # Restitution
> mf_export(map_Gard, width = 1500)
> mf_map(x = map_Gard, type = "typo", var = "CODE_CS", pal =  "RdYlGn" , border = NA, add = FALSE)
> mf_map(PGM_30, pch = 21, col = "red", cex = 1.5, add = TRUE)
>        
> mf_title("Gard")
> mf_arrow("topright")
> dev.off
> #> function (which = dev.cur()) 
> #> {
> #>     if (which == 1) 
> #>         stop("cannot shut down device 1 (the null device)")
> #>     .External(C_devoff, as.integer(which))
> #>     dev.cur()
> #> }
> #> <bytecode: 0x000000001d05bee0>
> #> <environment: namespace:grDevices>
> ```
> 
> Created on 2022-08-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)

The last line should be `dev.off()`.

**Comment by rCarto** [comment]
> I try this :
> 
> ```r
> # Palette_2
> hcl.pals("diverging")
> #>  [1] "Blue-Red"      "Blue-Red 2"    "Blue-Red 3"    "Red-Green"    
> #>  [5] "Purple-Green"  "Purple-Brown"  "Green-Brown"   "Blue-Yellow 2"
> #>  [9] "Blue-Yellow 3" "Green-Orange"  "Cyan-Magenta"  "Tropic"       
> #> [13] "Broc"          "Cork"          "Vik"           "Berlin"       
> #> [17] "Lisbon"        "Tofino"
> my_pal2 <- hcl.colors(n = 11,  palette = "Red-Green", rev = TRUE)
> cols <- mf_get_pal(n = c(5, 6), pal = c("Reds 2", "Greens"), rev = c(FALSE, TRUE))
> #> Error in mf_get_pal(n = c(5, 6), pal = c("Reds 2", "Greens"), rev = c(FALSE, : impossible de trouver la fonction "mf_get_pal"
> plot(1:11, rep(1, 11), bg = cols, pch = 22, cex = 4)
> #> Error in plot.xy(xy, type, ...): objet 'cols' introuvable
> ```
> 
> ![](https://camo.githubusercontent.com/705e4028e9b8cc12ade8f49f054e285a797674fa07b2c5e80c5775e55e9c2821/68747470733a2f2f692e696d6775722e636f6d2f385749677371722e706e67)
> 
> ```r
> mf_map(x = map_Gard, type = "typo", var = "CODE_CS", pal =  "Red-Green" , border = NA, add = FALSE, rev = TRUE)
> #> Error in mf_map(x = map_Gard, type = "typo", var = "CODE_CS", pal = "Red-Green", : impossible de trouver la fonction "mf_map"
> ```
> 
> Created on 2022-08-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)

You should start the script with `library(mapsf)`.

**Comment by rCarto** [comment]
You can read these parts : 
https://rcarto.github.io/cartographie_avec_r/les-types-de-cartes.html#palettes
and
https://rcarto.github.io/cartographie_avec_r/les-types-de-cartes.html#carte-de-typologie
