### ISSUE TITLE
The bg argument seems to not working

### ISSUE THREAD

**Issue by Nowosad** [riatelab/mapsf#38]
Hi @rCarto -- see my reprex below:

``` r
# remotes::install_github("riatelab/mapsf")
library(mapsf)
#> Loading required package: sf
#> Linking to GEOS 3.9.2, GDAL 3.3.2, PROJ 8.2.1; sf_use_s2() is TRUE
mtq = mf_get_mtq()
mf_map(mtq, bg = "lightblue")
```

![](https://i.imgur.com/KAhiZ1G.png)

<sup>Created on 2022-02-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rCarto** [comment]
Hi @Nowosad , 
That's true. `mf_map(x, type = "base",...)` is mostly a wrapper around `plot(st_geometry(x), ...)` and most of the arguments from `plot.sfc_*` are usable, but not this particular one.
Graphical parameters related to the figure itself (margins, background color, foreground color, + title params) are to be set with `mf_theme()` and are persistent across maps. 
See:
``` r
library(mapsf)
#> Le chargement a nécessité le package : sf
#> Linking to GEOS 3.9.0, GDAL 3.2.2, PROJ 7.1.0; sf_use_s2() is TRUE
mtq <- mf_get_mtq()
mf_theme(bg = "lightblue", mar = c(0,0,0,0))
mf_map(mtq)
```

![](https://i.imgur.com/PLPIAjB.png)

<sup>Created on 2022-02-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Do you think I should add a note in the documentation with this statement?

**Comment by Nowosad** [comment]
@rCarto thanks for the answer. So, does `bg` argument have any use in `mf_map()`? If not -- maybe it is better to remove it. On the other hand, if this argument has some (limited) use then an update to its documentation would be good.

**Comment by rCarto** [comment]
Removed, thanks!
