### ISSUE TITLE
Impossible to turn polygon borders transparent in mf_map

### ISSUE THREAD

**Issue by FNRobinne** [riatelab/mapsf#44]
When working with large polygon datasets, it would be nice to make polygon borders transparent, or of the same color as the polygon fill color, otherwise it's impossible to see the color palette. Having such option for the `border` argument or the `lwd` argument would be great. I tried `lwd=0` but got an error back.

**Comment by rCarto** [comment]
Have you tried border=NA?

**Comment by FNRobinne** [comment]
Oh, yes, it worked! Thanks. Perhaps add a line in one of the vignettes?
Merci!
