### ISSUE TITLE
mapsf - possible to make compatible with tidyverse piping?

### ISSUE THREAD

**Issue by AmyMikhail** [riatelab/mapsf#57]
I am interested to try this package as it looks like it could give me a nice choropleth map with much less code than I am currently using to produce the map using `ggplot()` and `geom_sf()`.

I tried copying the code from the vignette to produce a choropleth map in an R markdown chunk, and managed to produce a map.  I also managed to produce one with my own data and slightly different settings.  However I noticed that I could not see or initiate the plot window unless I ran the whole chunk and also couldn't figure out the following:

1. Why is the map not assignable to an object name?  
2. Related to this, how does each additional layer / feature 'know' to add it to the preceding layer/feature?
3. Also related to the above, it does not seem to be possible to use a `+` or a pipe operator `%>%` to link the instructions to build each layer.  This means one has to repeat the name of the data to use each time (except apparently for `mf_layout()` which I find unintuitive).

My confusion about the syntax is partly informed by having switched to tidyverse, dplyr code and piped workflows almost exclusively some months ago, as I find this very convenient and it also seemed like a lot of packages were being developed with tidyverse compatibility in mind (including for example the `sf` package). 

It would be helpful to understand how I can access any maps made with this package as r objects, so that I can interrogate them further or do other things with them later.  For example, I would like to know what package is being used to make the map under the hood, if it is ggplot as this would mean I could add other features to it using ggplot syntax. But without an object name, I can't even do `str(mymap)` so I'm a bit lost.

I can see from the package documentation that it is intended both for R users and for people that normally use Qgis etc. who want to switch to R. Given this, I think there is a strong case for the map object itself being accessible, since most R users would expect this?

If the map could be assigned a name and work with pipes it would be much more intuitive for regular R and tidyverse users, like so:

```
# Proposed syntax with object name and piped workflow:

# Get example data from package:
study_map <- mf_get_mtq() %>% 
  mutate(POPDENS = 1e6 * POP / st_area(study_map)) %>% 

  # Initiate plot window: 
  mf_init(expandBB = rep(0, 4), 
          theme = 'dark') %>% 
  
  # Add shadow map:
  mf_shadow(col = 'magenta', 
            cex = 2, 
            add = TRUE) %>% 
  
  # Add title and credits:
  mf_layout(title = 'Martinique',
            credits = paste0('Sources: IGN, 2018
                             \nAuthor: Wyclife Agumba Oluoch
                             \n',
                             'Package: mapsf ',
                             packageVersion('mapsf'))) %>% 
  
  # Add choropleth map:
  mf_map(var = "POPDENS", 
         type = "choro", 
         breaks = "geom", 
         nbreaks = 5,
         col = "Mint", 
         border = "white", 
         lwd = 0.5, 
         leg_pos = "topright", 
         leg_title = "Population Density\n(people per km2)", 
         add = TRUE)

```

Maybe with this syntax an explicit call to initiate the plot window wouldn't be necessary (I notice some of the examples in the vignette are without this) but not sure.

**Comment by rCarto** [comment]
Hello,
Thank you for your contribution.
I'm AFK right now, so it's just a short answer to your questions. 

`mapsf` is unambiguously closer to the R base than to the tidyverse. `mf_map()` behaviour is similar to the behaviour of `plot()`. The tidyverse way is not the only way 😄 . 

You should have a look at the `tmap` package that may very well suit you needs. It's also a thematic cartography package but with a syntax *à la* `ggplot2` .

That being said, I have a WIP package that transform `mapsf` to be used exactly the way you'd like. 😅

**Comment by rCarto** [comment]
> That being said, I have a WIP package that transform `mapsf` to be used exactly the way you'd like. 😅

Something like that: 
https://gist.github.com/rCarto/12cc0020852024b7c358087188f6515c

**Comment by AmyMikhail** [comment]
Thanks @rCarto this looks like what I was after - will you be adding it to `mapsf` or putting it in another package?

Also, just one question - in the example code above I noticed you had to mention the data set source several times, even after piping - just curious, if the data `mtq` was piped *before* any of the `ps_map` functions, would they inherit the data source so no need to mention it in the next line?  

I'm aware that `ggplot()` also doesn't do this as smoothly as expected (you can pipe a data set into the very first ggplot command and the first `geom()` will inherit it, but not subsequent ones - not sure of the reason for this).

**Comment by rCarto** [comment]
> Thanks @rCarto this looks like what I was after - will you be adding it to `mapsf` or putting it in another package?

I don't really know what to do with this. I'm not sure it will even be published anywhere...

> Also, just one question - in the example code above I noticed you had to mention the data set source several times, even after piping - just curious, if the data `mtq` was piped _before_ any of the `ps_map` functions, would they inherit the data source so no need to mention it in the next line?

What is piped in these functions is not an sf data.frame. It's rather a "map" object that grows progressively as layers are added. A map can use multiple data sources to create multiple layers. See:

``` r
library(sf)
#> Linking to GEOS 3.11.1, GDAL 3.6.2, PROJ 9.1.1; sf_use_s2() is TRUE
com <- st_read('/home/tim/lot46.gpkg', "commune", quiet = T)
road <- st_read('/home/tim/lot46.gpkg', "route", quiet = T)
resto <- st_read('/home/tim/lot46.gpkg', "restaurant", quiet = T)

pf_map(x = com, type = "base", col = "lightblue") |>
  pf_map(x = com, var = "POPULATION", type = "prop") |>
  pf_map(x = road, type = "base", lwd = .5, col = "grey") |>
  pf_map(x = resto, type = "base", pch = 21, cex = .5) |>
  pf_layout(title = "Municipalities, roads, retaurants...", 
            arrow = F, frame = TRUE) |>
  pf_theme(x = "candy", pos = "center") |>
  pf_plot()
```

![](https://i.imgur.com/aWcYxZk.png)

<sup>Created on 2023-09-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
