### ISSUE TITLE
Black rectangle drawn instead of map

### ISSUE THREAD

**Issue by asitemade4u** [riatelab/mapsf#61]
Hi,
I am facing an issue when trying to map a `sf` spatial dataset.

1. I have reproduced successfully your textbook example of the Martinique island
2. Yet, when I follow the exact same steps as your textbook example I get a black rectangle as a `png` file.

I have checked:

1. the validity of the geometries (`MULTIPOLYGON`) of my geospatial dataframe using `sf::st_make_valid( )`
2. I get no error while executing the whole procedure
3. I can display the spatial dataframe without issue using MapView

What am I doing wrong?

- Is it because the spatial dataframe has **2225** features?
- Is there a limit to the number of polygons that can be displayed using `mapsf`?
- If so, is there a way to increase the limit?

Thank you for your help,
S.

**Comment by rCarto** [comment]
Hi, 
There is no limit to the number of polygons you can display with `mapsf`. 
Are you using `mf_export()` ? Are x arguments in `mf_export()` and the following `mf_map()` call the same?

Can you share your code and data so I can reproduce the error? I can't help much without them.

**Comment by rCarto** [comment]
Well yes, see [help page ](https://riatelab.github.io/mapsf/reference/mf_export.html) and [vignette](https://riatelab.github.io/mapsf/articles/web_only/how_to_export_maps.html).
