### ISSUE TITLE
Make Head/Tails algorithm readily available in mapsf

### ISSUE THREAD

**Issue by asitemade4u** [riatelab/mapsf#63]
Hi,
Fisher/Jenks algorithm is generally considered the most usual, and as such has been adopted by most cartographic tools as their default when drawing choropleth maps.
However, Head/Tails algorithm (Bin Jiang, 2011) has a lot of advantages, notably when depicting heavy-tailed distributions -- which is what I am dealing with in immigration demographics in NYC.
Would you implement it in `mapsf`, which should not be too complicated as `mapsf` relies on `ClassInt`, which, in turn, implements it by default?

Thank you,
S.

**Comment by rCarto** [comment]
It's already there :
``` r
library(mapsf)
mtq <- mf_get_mtq()
mf_get_breaks(x = mtq$MED,breaks = "headtails", thr = .5)
#> [1] 11929.00 16137.71 18377.87 19813.29 21383.00 21761.00
mf_map(mtq, "MED", "choro", breaks = "headtails")
```

![](https://i.imgur.com/tXVIjkW.png)

<sup>Created on 2024-02-16 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
