### ISSUE TITLE
Unable to change position of credits

### ISSUE THREAD

**Issue by asitemade4u** [riatelab/mapsf#64]
Hi,
I am drawing a map using `mapsf` and I have an issue with `mf_credits` only: whatever the parameter I pass to `pos`(`center`, `rightbottom`, `bottomright`), I cannot get the credits aligned to another position than bottom-left.

Here is my code:
```R
mapsf::mf_credits(glue::glue("By Census Tracts, {clsnam}\nSource: IPUMS. 2023. http://doi.org/10.18128/D050.V18.0", cex = 0.7, pos = "bottomright", col = "#000000"))
```
And here is the result I get:

![1920-ger (2)](https://github.com/riatelab/mapsf/assets/11460106/5e477437-3e3a-45c6-8659-2a311a5dbcf3)

Am I missing something?
Thanks,
S.

**Comment by rCarto** [comment]
I see: 
``` r
library(mapsf)
mtq <- mf_get_mtq()
mf_map(mtq)
mf_credits(txt = "pos = bottomright", pos = "bottomright")
mf_credits(txt = "pos = bottomleft", pos = "bottomleft")
mf_credits(txt = "    pos = rightbottom", pos = "rightbottom")
```

![](https://i.imgur.com/t9uJeOo.png)

<sup>Created on 2024-02-20 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Can you provide a reproducible example (available data & code, no extra packages)?

**Comment by rCarto** [comment]
your parentheses are in the wrong place
