### ISSUE TITLE
Add a "line type" (lty) argument ?

### ISSUE THREAD

**Issue by HuguesPecout** [riatelab/mapsf#66]
It would be nice to be able to modify the line type (as the "lty" argument for the plot function). This would be particularly useful for 'typo' maps applied on lines.

**Comment by rCarto** [comment]
Can you be a bit more specific on your needs? Should it be equivalent to pch for "symb" maps but used when input are lines?

**Comment by rCarto** [comment]
This already works with "base" type. I'll think about how to use it in other types.
