### ISSUE TITLE
could this be used for China data?

### ISSUE THREAD

**Issue by LiXingguangBrandonStark** [riatelab/mapsf#7]
I want to visualization the data from China, how can i do that, thanks.

**Comment by rCarto** [comment]
Of course you can. You can map any basemap imported via `sf`. Have a look at natural earth or gadm websites to download data for example. Alternatively you can use `rnaturalearth` package or `getData()` from `raster` package to download and import basemaps directly in R. Other packages may exist on China basemap, you can check it on CRAN.

**Comment by LiXingguangBrandonStark** [comment]
@rCarto thanks, this is great package to me.

**Comment by rCarto** [comment]
@LiXingguangBrandonStark , 
You can also check [`rgeoboundaries`](https://github.com/wmgeolab/rgeoboundaries).

**Comment by LiXingguangBrandonStark** [comment]
thanks

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
