### ISSUE TITLE
Bordure blanche lors de l'export d'un raster

### ISSUE THREAD

**Issue by mgageo** [riatelab/mapsf#70]
J'exporte en format png un raster chargé avec terra.
Sur l'image png, le raster est bordé par une bande blanche, même en mettant à zéro les marges.

```
  dsn <- dsn <- "https://github.com/mgageo/issues/raw/main/ortho_3232443.tif"
  img <- rast(dsn)
  dsn <- "mapsf.png"
  mf_export(
    x = img,
    filename = dsn,
    width = 2048,
    expandBB = c(0, 0, 0, 0),
  )
  mf_raster(img)
  dev.off()
```

**Comment by rCarto** [comment]
Bonjour, 
Les marges de la figures sont gérées avec la fonction `mf_theme()`. Il faut toujours utiliser `add = TRUE` après l'utilisation de `mf_export()`.
``` r
library(mapsf)
library(terra)
#> terra 1.7.78
dsn <- "https://github.com/mgageo/issues/raw/main/ortho_3232443.tif"
img <- rast(dsn)
dsn <- "mapsf.png"
# use mf_theme() to set margins
mf_theme(mar = c(0, 0, 0, 0))
mf_export(
  x = img,
  filename = dsn,
  width = 2048
)
# always use add = TRUE after mf_export()
mf_raster(img, add = TRUE)
dev.off()
#> png 
#>   2
```

<sup>Created on 2024-06-18 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>



![mapsf.png](https://github.com/riatelab/mapsf/assets/3041254/3eceaa72-f834-43c6-98ae-9e3f884e810f)
