### ISSUE TITLE
(suggestion) Add minimal R version

### ISSUE THREAD

**Issue by Bakaniko** [riatelab/mapsf#8]
Hi,

By convenience, I use an old version of R (3.5.3).
When installing, `hcl.colors` was missing because it has been [introduced in R 3.6.0](https://stackoverflow.com/questions/65993395/rgl-package-has-non-zero-status).

I think that providing an information on R minimal version can be useful.
I perfectly understand that it can be cumbersome to test install against several versions.

This suggestion is also there to document that installation issue.
I also have R 4.0.4 and mapsf installed perfectly against it.

**Comment by rCarto** [comment]
Hi, 
You're right. I changed the minimal version number to 3.6.0 in the dev version (see also https://github.com/riatelab/mapsf/issues/4).
