### ISSUE TITLE
mf_worldmap additional arguments

### ISSUE THREAD

**Issue by tnederlof** [riatelab/mapsf#9]
I noticed with mf_worldmap there are some hard coded values in the plot function for the water background, land and overall insert frame. For some backgrounds I want to remove the frame or change the colors. My first thought is to capture more parameters via ... and check if they exist before entering the default (as is the case with the points). I would be happy to contribute but wanted to check in first.

**Comment by rCarto** [comment]
Yes, that's a good idea. A PR would be welcomed. 
I think it may be a bit difficult to remove the frame for insets in general.

**Comment by rCarto** [comment]
@tnederlof, the frame problem is solved. Feel free to re-open the issue if you come up with a solution to add additional args.
